POST http://localhost:3000/users
content-type: application/json

{
  "name": "John",
  "surname":"Doe"
}

###
GET http://localhost:3000/users

###
POST http://localhost:3000/credentials/9
content-type: application/json

{
  "email": "johndoe@johndoe.com.br",
  "password":"123456"
}

###
POST http://localhost:3000/genres
content-type: application/json

{
  "name": "Esportes"
}

###
POST http://localhost:3000/games
content-type: application/json

{
  "game": "Fifa 2020",
  "genre_id": 1
}
