version: '3'

services:
  app:
    build: .
    entrypoint: ./.docker/entrypoint.sh
    container_name: nestjs-cadastro
    ports:
      - 3000:3000
      - 5555:5555 #Porta onde roda o prisma studio
    volumes:
      - .:/home/node/app

